Repository connect-foundation/2019-06, pull requests merged in 2019-12, with the labels that each got.

#243 BE 첨부파일 Storage 저장
  server/dev.env
  server/mock/create-large-amount-data.js
  server/package-lock.json
  server/package.json
  server/src/database/models/attachment.js
  server/src/libraries/mail-util.js
  server/src/libraries/storage/ncloud.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
  server/test/attachment/database.spec.js
Labels: 🏭BE

#248 [FE] 모두를 위한 Snackbar(alert) 컴포넌트 추가
  web/components/Aside/dialog-data.js
  web/components/Aside/index.js
  web/components/Snackbar/content.js
  web/components/Snackbar/index.js
  web/package.json
  web/pages/login.js
Labels: 🎨FE

#249 [BE] mail model에서 message id를 기록할 컬럼 추가
  server/src/database/models/mail.js
Labels: 📚DB

#259 [FE] 메일 내게 쓰기 구현
  web/components/Aside/index.js
  web/components/WriteMail/DropZone/index.js
  web/components/WriteMail/InputBody/index.js
  web/components/WriteMail/InputReceiver/index.js
  web/components/WriteMail/InputSubject/index.js
  web/components/WriteMail/ReservationDateText/index.js
  web/components/WriteMail/ReservationTimePicker/index.js
  web/components/WriteMail/SubmitButton/index.js
  web/components/WriteMail/index.js
  web/components/WriteMailToMe/index.js
  web/pages/mail/write.js
Labels: 🎨FE

#266 [BE/Infra] 내게 쓰기
  server/src/bin/www.js
  server/src/libraries/save-to-infra.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
Labels: infra, 🏭BE

#276 [FE] 첨부파일 화면/스낵바 refactor/메일전송 실패 메세지
  web/components/Aside/dialog-data.js
  web/components/GlobalStyle/index.js
  web/components/MailArea/index.js
  web/components/ReadMail/FileList/File/index.js
  web/components/ReadMail/FileList/File/styled.js
  web/components/ReadMail/FileList/index.js
  web/components/ReadMail/FileList/styled.js
  web/components/ReadMail/index.js
  web/components/ReadMail/styled.js
  web/components/Snackbar/index.js
  web/components/WriteMail/DropZone/index.js
  web/components/WriteMail/InputBody/index.js
  web/components/WriteMail/InputReceiver/index.js
  web/components/WriteMail/InputSubject/index.js
  web/components/WriteMail/ReservationDateText/index.js
  web/components/WriteMail/ReservationTimePicker/index.js
  web/components/WriteMail/SubmitButton/index.js
  web/components/WriteMail/index.js
  web/components/WriteMailToMe/index.js
Labels: 🎨FE

#287 [FE] Snackbar 수정 및 Dropzone Toggle / 내게쓰기 메일쓰기 Toggle
  web/components/Aside/dialog-data.js
  web/components/Aside/index.js
  web/components/MailArea/index.js
  web/components/ReadMail/FileList/index.js
  web/components/ReadMail/FileList/styled.js
  web/components/Snackbar/index.js
  web/components/WriteMail/DropZone/index.js
  web/components/WriteMail/InputReceiver/styled.js
  web/components/WriteMail/Tools/ChangeWriteAreaButton/index.js
  web/components/WriteMail/Tools/Message.js
  web/components/WriteMail/Tools/SwitchDropzone/index.js
  web/components/WriteMail/Tools/index.js
  web/components/WriteMail/Tools/styled.js
  web/components/WriteMail/index.js
  web/components/WriteMailToMe/index.js
  web/contexts/reducer.js
  web/pages/index.js
Labels: 🎨FE

#290 [BE] 메일 보낼 때 메세지 아이디도 함께 저장
  server/src/libraries/mail-util.js
  server/src/v1/mail/service.js
Labels: 🏭BE

#295 feat(fe): 전체메일함 클릭시 각 메일이 어디 메일함에 들어있는지 보이도록 추가
  web/components/MailArea/MailTemplate/index.js
  web/components/MailArea/MailTemplate/styled.js
  web/components/MailArea/index.js
Labels: 🎨FE

#329 fix(be/mail): 메일리스트 시간정렬 #313
  server/src/v1/mail/service.js
  server/test/libraries/mail/attachment.spec.js
  server/test/mail/api.spec.js
  server/test/mail/service.spec.js
Labels: 🏭BE, 😱bug

#333 [FE] 메일함 추가/수정/삭제 버그 fix
  web/components/Aside/dialog-data.js
  web/components/Aside/index.js
Labels: 🎨FE

#335 fix(be): imap 에러처리 추가
  server/src/libraries/save-to-infra.js
  server/src/v1/mail/box/service.js
Labels: 🏭BE

#341 fix(fe/mail): 메일페이지 css조정 #319
  web/components/Aside/index.js
  web/components/Aside/styled.js
  web/components/Error/Server/index.js
  web/components/Error/User/index.js
  web/components/Footer/styled.js
  web/components/GlobalStyle/index.js
  web/components/Header/index.js
  web/components/Header/styled.js
  web/components/MailArea/index.js
  web/components/ReadMail/FileList/index.js
  web/components/ReadMail/styled.js
  web/components/WriteMail/styled.js
  web/public/logo.png
Labels: 🎨FE, 😱bug

#353 [BE] Hotfix - 메일 전송시 메세지 아이디 뒤에 도메인 추가
  server/src/libraries/mail-util.js
Labels: 🏭BE

#354 [BE] id로 가입한 회원과 sub_email로 가입한 회원이 서로 다를 경우 처리
  server/src/database/models/user.js
  server/src/v1/users/service.js
Labels: 🚑hotfix

#365 [BE] mime message date 수정
  server/src/libraries/mimemessage.js
  server/src/v1/mail/service.js
Labels: 🏭BE

#366 [Infra] 작업 동기화
  infra/maildb/node-runner.sh
  infra/maildb/src/app.js
  infra/maildb/src/env.js
  infra/maildb/src/format.js
  infra/maildb/src/package-lock.json
  infra/maildb/src/package.json
  infra/postfix/advanced-content-filter.py
Labels: infra

#379 [BE] imap 서버와 연결하여 메일 이동시키기
  server/src/libraries/exception/error-code.js
  server/src/libraries/mail-util.js
  server/src/libraries/save-to-infra.js
Labels: infra, 🏭BE

#416 [BE] IMAP 메일함/메일의 정보와 DB 메일함/메일의 정보 동기화
  server/src/database/models/mail.js
  server/src/libraries/imap.js
  server/src/libraries/mail-util.js
  server/src/libraries/save-to-infra.js
  server/src/middlewares/sync-with-imap.js
  server/src/v1/admin/mail/service.js
  server/src/v1/auth/index.js
  server/src/v1/mail/box/service.js
  server/src/v1/mail/service.js
Labels: 🌈feature, 🏃‍♀️priority:high, 🏭BE, 📚DB

#428 [FE] 여러 메일 복붙시 파싱/메일 전송 버튼 버그
  web/components/WriteMail/InputReceiver/index.js
  web/components/WriteMail/Tools/index.js
  web/package-lock.json
Labels: 🎨FE, 😱bug

#429 [BE] 로그인할 때 IMAP과 DB 메일/메일함 동기화 실패시 에러처리 추가
  server/src/libraries/exception/error-code.js
  server/src/middlewares/sync-with-imap.js
  server/src/v1/auth/controller.js
Labels: 🏭BE, 😱bug

#440 [FE] 변수명 수정
  web/components/Aside/dialog-data.js
  web/components/Aside/index.js
Labels: 🙄chore

#442 [FE/Hotfix] get dialog부분 bug hotfix
  web/components/Aside/dialog-data.js
  web/components/Aside/index.js
Labels: 🎨FE, 😱bug

#444 [FE] dialog parameter 객체화
  web/components/Aside/dialog-data.js
  web/components/Aside/index.js
Labels: 🙄chore

#445 perPageNum이 변경된 후 이전/다음 메일 보기 버그 수정 #439
  web/components/Aside/index.js
  web/components/MailArea/MailTemplate/index.js
  web/components/MailArea/Tools/index.js
  web/components/MailArea/index.js
  web/components/ReadMail/PageMoveButtonArea/index.js
  web/components/ReadMail/Tools/index.js
  web/components/ReadMail/index.js
Labels: 🎨FE, 🚑hotfix

#451 [BE] imap과 sync맞추는 부분에서 get db mails 함수 for문 하나 줄임
  server/src/database/models/mail.js
  server/src/middlewares/sync-with-imap.js
Labels: performance, 🏭BE

#459 [Infra] 메일 저장할 때 mail 테이블에 has attachment 추가 저장
  infra/maildb/src/format.js
Labels: infra, 😱bug

#460 [BE] 메일 저장시 has attachments를 has attachment로 수정
  server/src/v1/mail/service.js
Labels: 🏭BE, 😱bug

#461 [FE] refactor(리뷰지적부분)
  web/components/Aside/dialog-data.js
  web/components/WriteMail/Tools/index.js
Labels: 🎨FE

#465 [BE] 내게쓰기 꺾쇄 들어가던 부분 수정 / 받은 메일함으로 이동시에도 메일함 이름 수정
  server/src/libraries/imap.js
  server/src/v1/mail/service.js
Labels: 🏭BE, 😱bug
