Repository connect-foundation/2019-06, pull requests merged in 2019-11, with the labels that each got.

#23 feat: create directories in master branch
  infra/index.js
  server/index.js
  web/index.js
Labels: feature

#28 chore: commitlint, prettier, eslint config
  web/.commitlintrc.json
  web/.eslintrc.json
  web/.huskyrc
  web/.lintstagedrc
  web/.prettierrc
  web/components/nav.js
  web/package.json
  web/pages/index.js
  web/yarn.lock
Labels: 🙄chore

#32 feat: editorconfig
  web/.editorconfig
  web/.huskyrc
  web/.lintstagedrc
  web/package-lock.json
Labels: 🎨FE, 🙄chore

#41 Fe/develop
  web/.prettierignore
  web/package-lock.json
  web/package.json
  web/pages/_app.js
  web/pages/_document.js
  web/pages/index.js
  web/yarn.lock
Labels: 🎨FE

#42 Be/develop
  server/package-lock.json
  server/package.json
  server/src/bin/dbSync.js
  server/src/bin/www.js
  server/src/database/makeData.js
Labels: 🏭BE

#44 feat: layout in index page
  web/.babelrc
  web/.eslintrc.json
  web/components/index/Aside/CategoryCard/index.js
  web/components/index/Aside/CategoryCard/styled.js
  web/components/index/Aside/index.js
  web/components/index/Aside/styled.js
  web/components/index/Header/index.js
  web/components/index/Header/styled.js
  web/components/index/MailArea/index.js
  web/components/index/MailArea/styled.js
  web/components/index/Tools/index.js
  web/components/index/Tools/styled.js
  web/components/index/styled.js
  web/pages/_app.js
  web/pages/index.js
Labels: 🎨FE

#45 fix: routes폴더 v1폴더로 변경
  server/.babelrc
  server/.huskyrc
  server/.lintstagedrc
  server/.prettierignore
  server/dev.env
  server/src/app.js
  server/src/v1/index.js
Labels: 🏭BE

#43 이름, 메일, 비밀번호, 유저 정보가 유효한지 확인
  server/src/utils/validator.js
  server/test/validator.spec.js
Labels: feature, 🏃‍♀️priority:high, 🏭BE

#53 feat: email tagging
  web/components/Send_Mail/Receiver_List/index.js
  web/components/Send_Mail/Receiver_List/styled.js
  web/components/Send_Mail/index.js
  web/pages/mail/send.js
  web/utils/validator.js
Labels: 🌈feature, 🎨FE

#54 회원가입 API 작성
  server/dev.env
  server/src/app.js
  server/src/database/create-dummy-data.js
  server/src/database/models/user.js
  server/src/libraries/buisiness-exception.js
  server/src/v1/index.js
  server/src/v1/users/index.js
  server/src/v1/users/users.ctrl.js
  server/test/users.spec.js
Labels: 🏭BE

#58 feat: add models #57
  server/src/database/models/address.js
  server/src/database/models/category.js
  server/src/database/models/classification-pattern-type.js
  server/src/database/models/classification-pattern.js
  server/src/database/models/mail.js
  server/src/database/models/user.js
Labels: 📚DB

#62 메일 작성 페이지 FE
  web/components/Send_Mail/Input_Body/index.js
  web/components/Send_Mail/Input_Body/styled.js
  web/components/Send_Mail/Input_Receiver/index.js
  web/components/Send_Mail/Input_Receiver/styled.js
  web/components/Send_Mail/Input_Subject/index.js
  web/components/Send_Mail/Input_Subject/styled.js
  web/components/Send_Mail/Submit_Button/index.js
  web/components/Send_Mail/Submit_Button/styled.js
  web/components/Send_Mail/context/index.js
  web/components/Send_Mail/index.js
  web/components/Send_Mail/styled.js
  web/package-lock.json
  web/package.json
Labels: 🌈feature, 🎨FE

#83 chore: add gitattributes #63
  server/.gitattributes
  server/LICENSE
  server/package.json
  server/src/app.js
  server/src/config/cookie.js
  server/src/libraries/notfound-exception.js
Labels: 🙄chore

#90 chore: add pre-push and test script
  server/.eslintrc.json
  server/.huskyrc
  server/package-lock.json
  server/package.json
  server/src/database/models/address.js
  server/src/database/models/mail-template.js
  server/src/database/models/mail.js
  server/src/v1/index.js
  server/test/address/database.spec.js
  server/test/attachment/database.spec.js
  server/test/mail/database.spec.js
  server/test/mail/service.spec.js
  server/test/mail_template/database.spec.js
  server/test/validator.spec.js
Labels: 🏭BE, 🙄chore

#94 merge 회원가입 refactoring
  server/package-lock.json
  server/package.json
  server/src/database/models/user.js
  server/src/libraries/exception/sequelize-error-parser.js
  server/src/libraries/validation/user.js
  server/src/v1/users/controller.js
  server/src/v1/users/service.js
  server/test/libraries/validation/user.spec.js
  server/test/user/api.spec.js
  server/test/user/database.spec.js
  server/test/user/integration.spec.js
  server/test/user/service.spec.js
  server/test/validator.spec.js
Labels: 🏭BE, 🗣discussion, 🙄chore

#95 메일 단일전송 #10 #11
  server/dev.env
  server/package-lock.json
  server/package.json
  server/src/database/models/mail-template.js
  server/src/libraries/error-code.js
  server/src/libraries/mail-util.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/index.js
  server/src/v1/mail/service.js
  server/test/attachment/database.spec.js
  server/test/libraries/mail/util.spec.js
  server/test/mail/api.spec.js
  server/test/mail/database.spec.js
  server/test/mail_template/database.spec.js
  server/test/user/database.spec.js
Labels: 🌈feature, 🏭BE, 📚DB, 🗣discussion

#99 메일리스트에 들어갈 query입니다. #98
  server/.mocharc.json
  server/mock/create-large-amount-data.js
  server/package-lock.json
  server/package.json
  server/src/database/models/mail.js
  server/test/address/database.spec.js
  server/test/mail/database.bulk.spec.js
  server/test/user/service.spec.js
Labels: 📚DB, 🗣discussion

#97 로그인 페이지 구현
  web/assets/imgs/logo.png
  web/components/Form/actions.js
  web/components/Form/index.js
  web/components/Form/reducers.js
  web/components/Form/styled.js
  web/components/GlobalStyle/index.js
  web/components/LinkArea/index.js
  web/components/LinkArea/styled.js
  web/components/SmallHeader/index.js
  web/components/SmallHeader/styled.js
  web/components/UserContext/index.js
  web/config/axios-config.js
  web/next.config.js
  web/package-lock.json
  web/package.json
  web/pages/_app.js
  web/pages/index.js
  web/pages/login.js
  web/utils/error-message.js
  web/utils/error-parser.js
  web/utils/validator.js
Labels: 🌈feature, 🎨FE

#105 fix: resolve passport login error
  server/src/config/cors-options.js
Labels: 🚑hotfix

#110 fix: resolve passport login error
  web/pages/_app.js
Labels: 🚑hotfix

#112 prettier script 추가
  web/.prettierignore
  web/package.json
  web/pages/_document.js
Labels: 🎨FE

#111 prettier script 추가, 통과되지 않는 테스트 코드 삭제
  server/package.json
  server/test/user/api.spec.js
  server/test/user/database.spec.js
Labels: 🏭BE

#115 리뷰에 따라 sql query문 변경
  infra/maildb/controller.sh
  infra/maildb/init.sh
  infra/maildb/node-runner.sh
  infra/maildb/src/app.js
Labels: infra, 👷🏽security

#116 회원가입 페이지 작성
  web/components/GlobalStyle/index.js
  web/components/RegisterForm/index.js
  web/components/RegisterForm/styled.js
  web/components/RegisterLogo/index.js
  web/components/RegisterLogo/styled.js
  web/pages/register.js
  web/utils/error-message.js
  web/utils/validator.js
Labels: 🌈feature, 🎨FE

#120 회원가입 페이지 에러 메시지 초기화 문제
  web/components/RegisterForm/index.js
  web/utils/validator.js
Labels: 🚑hotfix

#127 Be/develop
  .gitattributes
  server/.gitignore
  server/.huskyrc
  server/.mocharc.json
  server/src/app.js
  server/src/bin/dbSync.js
  server/src/database/models/mail.js
  server/src/database/models/user.js
  server/src/libraries/exception/error-code.js
  server/src/libraries/exception/error-field.js
  server/src/libraries/exception/error-response.js
  server/src/libraries/exception/sequelize-error-parser.js
  server/src/libraries/paging.js
  server/src/libraries/validation/mail.js
  server/src/middlewares/auth.js
  server/src/middlewares/validate-login.js
  server/src/middlewares/validate-user.js
  server/src/v1/auth/service.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
  server/src/v1/users/service.js
  server/test/address/database.spec.js
  server/test/libraries/mail/quey.spec.js
  server/test/libraries/paging.spec.js
  server/test/libraries/validation/user.spec.js
  server/test/mail/api.spec.js
  server/test/mail/database.bulk.spec.js
  server/test/mail/database.spec.js
  server/test/mail/service.spec.js
  server/test/user/api.spec.js
  server/test/user/service.spec.js
Labels: 🌈feature, 🏭BE

#130 [FE] layout
  web/components/Aside/index.js
  web/components/Aside/styled.js
  web/components/GlobalStyle/index.js
  web/components/WriteMail/DropZone/index.js
  web/components/WriteMail/DropZone/styled.js
  web/components/WriteMail/styled.js
  web/pages/index.js
Labels: 🎨FE

#129 [BE] 회원가입 시 default 카테고리 추가/ user_id -> id 변경
  server/mock/create-dummy-data.js
  server/src/database/models/category.js
  server/src/database/models/user.js
  server/src/libraries/parse-sequelize-error.js
  server/src/v1/users/service.js
  server/test/attachment/database.spec.js
  server/test/auth/service.spec.js
  server/test/libraries/validation/user.spec.js
  server/test/user/api.spec.js
  server/test/user/database.spec.js
  server/test/user/service.spec.js
Labels: 🏭BE, 📚DB

#131 Fe/develop 페이징 view를 만들어보았습니다.
  web/components/Aside/CategoryCard/index.js
  web/components/Aside/CategoryCard/styled.js
  web/components/Aside/index.js
  web/components/GlobalStyle/index.js
  web/components/Loading/index.js
  web/components/Loading/styled.js
  web/components/LoginForm/index.js
  web/components/MailArea/index.js
  web/components/MailTemplate/index.js
  web/components/Paging/PageNumber/index.js
  web/components/Paging/index.js
  web/components/Paging/styled.js
  web/contexts/index.js
  web/pages/_app.js
  web/pages/index.js
Labels: 🎨FE

#132 [server] 페이징처리시 category가 0일때 category를 필터에서 제거
  server/src/libraries/validation/mail.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
  server/test/libraries/mail/quey.spec.js
  server/test/mail/api.spec.js
  server/test/mail/service.spec.js
Labels: 🏭BE, 😱bug

#133 [BE] 메일 보내기 Hotfix
  server/src/libraries/mail-util.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
Labels: 🏭BE

#134 Fe/develop: 전역 컨텍스트 생성
  web/contexts/index.js
  web/contexts/reducer.js
  web/pages/_app.js
  web/pages/index.js
Labels: 🎨FE

#142 fe 페이징처리 & 카테고리처리 #72 #143
  web/components/Aside/index.js
  web/components/Footer/styled.js
  web/components/Loading/index.js
  web/components/Loading/styled.js
  web/components/MailArea/index.js
  web/components/MailTemplate/index.js
  web/components/Paging/PageNumber/index.js
  web/components/Paging/index.js
  web/components/Paging/styled.js
  web/contexts/index.js
  web/contexts/reducer.js
  web/pages/index.js
Labels: 🌈feature, 🎨FE

#141 fix(be/mail): 카테고리 필터가 미작동했던점 #140
  server/src/app.js
  server/src/database/models/mail.js
  server/src/libraries/validation/mail.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
  server/test/mail/service.spec.js
Labels: 🏭BE, 🚑hotfix

#152 [BE] 회원가입 암호화 알고리즘 변경
  server/src/database/models/user.js
  server/src/libraries/crypto.js
  server/src/middlewares/passport.js
  server/src/v1/auth/service.js
  server/src/v1/users/service.js
  server/test/crypto.spec.js
Labels: 🚑hotfix

#157 [BE/Infra] 보낸메일 인프라에 저장
  server/dev.env
  server/package-lock.json
  server/package.json
  server/src/database/models/mail.js
  server/src/libraries/mail-util.js
  server/src/libraries/mimemessage.js
  server/src/libraries/save-sent-mail.js
  server/src/middlewares/passport.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
Labels: infra, 🌈feature, 🏭BE

#171 fix: 페이징 처리 로직변경 및 폴더변경
  web/components/MailArea/Paging/PageNumber/index.js
  web/components/MailArea/Paging/index.js
  web/components/MailArea/index.js
Labels: 🎨FE

#175 refactor: mail-fetch방식 변경
  web/components/Aside/index.js
  web/components/Header/index.js
  web/components/MailArea/Paging/index.js
  web/components/MailArea/index.js
  web/components/MailTemplate/index.js
  web/components/ReadMail/PageMoveButtonArea/index.js
  web/components/ReadMail/index.js
  web/contexts/index.js
  web/contexts/reducer.js
  web/pages/index.js
  web/utils/query.js
  web/utils/request.js
  web/utils/use-fetch.js
Labels: 🎨FE

#177 [BE/Infra] 메일함 추가/수정/삭제
  server/mock/create-dummy-data.js
  server/mock/create-large-amount-data.js
  server/src/database/models/category.js
  server/src/libraries/exception/error-code.js
  server/src/libraries/save-sent-mail.js
  server/src/libraries/save-to-infra.js
  server/src/libraries/validation/mailbox.js
  server/src/v1/mail/box/controller.js
  server/src/v1/mail/box/index.js
  server/src/v1/mail/box/service.js
  server/src/v1/mail/index.js
  server/src/v1/mail/service.js
  server/test/mail_box/api.spec.js
Labels: infra, 🏭BE, 🚶‍♂️priority:middle

#201 FE 보낸사람, 제목기준 메일리스트정렬 #164 #165 #167 #168
  web/components/MailArea/Tools/index.js
  web/components/MailArea/Tools/styled.js
  web/components/MailArea/index.js
  web/components/MailArea/styled.js
  web/contexts/reducer.js
  web/utils/query.js
Labels: 🌈feature, 🎨FE

#200 BE 보낸사람, 제목기준 메일리스트정렬 #164 #165 #167 #168
  server/src/libraries/validation/mail.js
  server/src/v1/mail/controller.js
  server/src/v1/mail/service.js
  server/src/v1/users/service.js
  server/test/libraries/mail/quey.spec.js
  server/test/mail/service.spec.js
Labels: 🌈feature, 🏭BE

#207 feat(infra): advanced content filter python 코드 추가
  infra/postfix/advanced-content-filter.py
Labels: infra

#209 [BE] imap 서버 연결을 위한 User 테이블 imap_password 필드 추가
  server/dev.env
  server/src/database/models/user.js
  server/src/libraries/crypto.js
  server/src/v1/auth/controller.js
  server/src/v1/users/controller.js
  server/src/v1/users/service.js
  server/test/crypto.spec.js
  server/test/user/service.spec.js
Labels: 🏭BE

#208 BE 로깅 #205
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/libraries/logger/winston.js
Labels: 🏭BE, 🙄chore

#212 [hotfix] 로그아웃하고 다시 로그인하면 카테고리가 계속 누적되는 버그수정
  web/components/Aside/index.js
  web/components/MailArea/Tools/index.js
  web/components/MailArea/Tools/styled.js
  web/contexts/reducer.js
Labels: 😱bug, 🚑hotfix
